### ISSUE TITLE
Exception whilst adding relative reminder to newly created item

### ISSUE THREAD

**Issue by KoertLichtendonk** [olsh/todoist-net#24]
Hello, I'm getting an exception whilst adding a relative reminder to a newly created item. I can't seem to figure out what I'm doing wrong here. Any help would be appreciated.

The item is created and DueDate is correctly set, I also await the item creation. The exception is on the manager.Reminders.AddAsync async line.

**Exception**
```
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (Invalid argument value)
  Source=Todoist.Net
  StackTrace:
   at Todoist.Net.TodoistClient.ThrowIfErrors(SyncResponse syncResponse)
   at Todoist.Net.TodoistClient.<Todoist-Net-IAdvancedTodoistClient-ExecuteCommandsAsync>d__55.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Todoist.Net.Services.CommandServiceBase.<ExecuteCommandAsync>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Todoist.Net.Services.RemindersCommandService.<AddAsync>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Program.<<Main>$>d__0.MoveNext() in C:\Users\KLich\Source\Repos\KoertLichtendonk\TraktCalendarToTodoist\TraktCalendarToTodoist\Program.cs:line 42

Inner Exception 1:
TodoistException: Invalid argument value
```

**My code**
```
        Item calendarItem = new Item(show.Title)
        {
            DueDate = new DueDate(show.PublishDate.DateTime, false, _config.timezone)
        };

        ComplexId task = await todoistFactory.CreateTask(manager, calendarItem);

        if(!task.IsEmpty)
        {
            await manager.Reminders.AddAsync(new Reminder(task) { Type = ReminderType.Relative, MinuteOffset = 60 });
        }
```

**Comment by olsh** [comment]
This will be fixed in the next release.

Thank you! 👍🏻
